# Generated by Django 5.1.4 on 2025-02-18 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adviser', '0003_transaction_category_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adviser.category'),
        ),
    ]
