name: Django Deployment

on:
  push:
    branches:
      - master  # Change if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # Change if needed

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}  # Add in GitHub Secrets
      run: |
        python manage.py migrate

    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput

    - name: Start Gunicorn Server
      run: |
        gunicorn Fin_ai.wsgi:application --bind 0.0.0.0:8000
