name: Django Deployment

on:
  push:
    branches:
      - master  # Change if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # Change to your Python version

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file
      run: |
        echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
        echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env
        echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
        echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env
        echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env
        echo "TOGETHER_API_KEY=${{ secrets.TOGETHER_API_KEY }}" >> .env
        echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
        echo "DEBUG=${{ secrets.DEBUG }}" >> .env
      shell: bash

    - name: Run migrations
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        cd Fin_ai  # Navigate to the correct directory
        python manage.py migrate

    - name: Collect static files
      run: |
        cd Fin_ai  # Navigate to the correct directory
        python manage.py collectstatic --noinput

    - name: Start Gunicorn Server
      run: |
        cd Fin_ai  # Navigate to the correct directory
        gunicorn Fin_ai.wsgi:application --bind 0.0.0.0:8000
